#!/bin/bash
set -euo pipefail

WALLPAPER="${1:-}"
MODE_IN="${2:-}"

CACHE_DIR="$HOME/.cache/hypraceelerator"
STATE_FILE="$CACHE_DIR/state.env"
JSON_FILE="$CACHE_DIR/colors.json"

mkdir -p "$CACHE_DIR"

notify() {
    notify-send "Theme" "$1" -u "${2:-normal}" 2>/dev/null || true
}

if [[ -z "$WALLPAPER" && -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
    WALLPAPER="${WALLPAPER:-}"
fi

if [[ -z "$WALLPAPER" ]]; then
    notify "No wallpaper provided" critical
    exit 1
fi

if [[ ! -f "$WALLPAPER" ]]; then
    notify "Wallpaper not found: $WALLPAPER" critical
    exit 1
fi

if ! command -v matugen >/dev/null 2>&1; then
    notify "matugen not found" critical
    exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
    notify "jq not found" critical
    exit 1
fi

MODE="${MODE_IN,,}"
if [[ -z "$MODE" && -f "$STATE_FILE" ]]; then
    # Read only MODE from state; do not overwrite selected WALLPAPER.
    STATE_MODE=$(sed -n 's/^MODE="\(.*\)"$/\1/p' "$STATE_FILE" | head -n1 | tr '[:upper:]' '[:lower:]')
    if [[ -n "$STATE_MODE" ]]; then
        MODE="$STATE_MODE"
    fi
fi

if [[ "$MODE" != "dark" && "$MODE" != "light" ]]; then
    MODE="dark"
fi

set_wallpaper() {
    command -v swww >/dev/null 2>&1 || return 0

    if ! pgrep -x swww-daemon >/dev/null 2>&1; then
        swww-daemon >/dev/null 2>&1 &
        sleep 0.4
    fi

    swww img "$WALLPAPER" \
        --transition-type "grow" \
        --transition-duration 1.5 \
        --transition-fps 60 \
        --transition-bezier 0.65,0,0.35,1 >/dev/null 2>&1 && return 0

    sleep 0.2
    swww img "$WALLPAPER" \
        --transition-type "grow" \
        --transition-duration 1.2 \
        --transition-fps 60 \
        --transition-bezier 0.65,0,0.35,1 >/dev/null 2>&1 && return 0

    notify "Wallpaper apply failed (swww)" warning
    return 1
}

set_wallpaper || true

# Generate colors with matugen (single source of truth)
matugen image -j hex --quiet "$WALLPAPER" > "$JSON_FILE"

color() {
    local key="$1"
    jq -r --arg key "$key" --arg mode "$MODE" '.colors[$key][$mode]' "$JSON_FILE"
}

hex_to_rgba() {
    local hex="${1#\#}"
    local alpha="${2:-1}"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "rgba($r, $g, $b, $alpha)"
}

BG=$(color "background")
SURFACE=$(color "surface")
SURFACE_CONTAINER=$(color "surface_container")
SURFACE_CONTAINER_HIGH=$(color "surface_container_high")
TEXT=$(color "on_background")
TEXT_MUTED=$(color "on_surface_variant")
ACCENT=$(color "primary")
ACCENT2=$(color "secondary")
ACCENT3=$(color "tertiary")
OUTLINE=$(color "outline")
ERROR=$(color "error")

# Render themed SVG icons
ICON_DIR="$HOME/.config/waybar/icons"
TEMPLATE_DIR="$ICON_DIR/templates"
ICON_COLOR="$TEXT"

render_svg() {
    local src="$1"
    local dst="$2"
    sed "s/{{COLOR}}/${ICON_COLOR}/g" "$src" > "$dst"
}

render_battery() {
    local level="$1"
    local charging="$2"
    local file="$3"
    local fill_w
    fill_w=$(awk -v lvl="$level" 'BEGIN { printf "%.2f", (13.8 * lvl / 10.0) }')
    if [[ "$level" -le 0 ]]; then
        fill_w="0"
    fi
    cat > "$file" << EOF
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">
  <rect x="2.8" y="7" width="17" height="10" rx="2.4" ry="2.4" stroke="${ICON_COLOR}" stroke-width="1.9"/>
  <rect x="19.9" y="10" width="1.6" height="4" rx="0.8" fill="${ICON_COLOR}"/>
EOF
    if [[ "$level" -gt 0 ]]; then
        cat >> "$file" << EOF
  <rect x="4.2" y="8.6" width="${fill_w}" height="6.8" rx="1.1" fill="${ICON_COLOR}"/>
EOF
    fi
    cat >> "$file" << EOF
</svg>
EOF
}

if [[ -d "$TEMPLATE_DIR" ]]; then
    for tpl in "$TEMPLATE_DIR"/*.svg; do
        [[ -f "$tpl" ]] || continue
        name=$(basename "$tpl")
        render_svg "$tpl" "$ICON_DIR/$name"
    done

    for i in $(seq 0 10); do
        render_battery "$i" 0 "$ICON_DIR/battery-$i.svg"
        render_battery "$i" 1 "$ICON_DIR/battery-charging-$i.svg"
    done
fi

# Hyprland colors
cat > "$HOME/.config/hypr/colors-dynamic.conf" << EOF
# Auto-generated by matugen
# Source: $(basename "$WALLPAPER")

\$accent1 = ${ACCENT}
\$accent2 = ${ACCENT2}
\$outline = ${OUTLINE}
\$surface = ${SURFACE}

general {
    col.active_border = rgba(${ACCENT:1}ff) rgba(${ACCENT2:1}ff) 45deg
    col.inactive_border = rgba(${OUTLINE:1}66)
}
EOF

# Waybar colors
cat > "$HOME/.config/waybar/colors.css" << EOF
/* Auto-generated by matugen */
/* Source: $(basename "$WALLPAPER") */

@define-color bg-base $(hex_to_rgba "$BG" 0.82);
@define-color bg-surface $(hex_to_rgba "$SURFACE_CONTAINER" 0.92);
@define-color bg-hover $(hex_to_rgba "$SURFACE_CONTAINER_HIGH" 0.88);
@define-color bg-active $(hex_to_rgba "$ACCENT" 0.18);

@define-color text-primary ${TEXT};
@define-color text-secondary ${TEXT_MUTED};

@define-color accent-primary ${ACCENT};
@define-color accent-secondary ${ACCENT2};
@define-color accent-tertiary ${ACCENT3};

@define-color warning ${ERROR};
@define-color critical ${ERROR};
@define-color success ${ACCENT2};
EOF

# Swaync colors
cat > "$HOME/.config/swaync/colors.css" << EOF
/* Auto-generated by matugen */
/* Source: $(basename "$WALLPAPER") */

@define-color bg $(hex_to_rgba "$SURFACE" 0.94);
@define-color bg-solid ${SURFACE};
@define-color bg-hover $(hex_to_rgba "$SURFACE_CONTAINER" 0.94);
@define-color bg-focus $(hex_to_rgba "$SURFACE_CONTAINER_HIGH" 0.94);
@define-color bg-widget $(hex_to_rgba "$SURFACE_CONTAINER" 0.9);

@define-color text ${TEXT};
@define-color text-secondary ${TEXT_MUTED};
@define-color text-dim ${TEXT_MUTED};

@define-color accent ${ACCENT};
@define-color accent-light $(hex_to_rgba "$ACCENT" 0.2);
@define-color accent2 ${ACCENT2};

@define-color border $(hex_to_rgba "$OUTLINE" 0.4);
@define-color border-light $(hex_to_rgba "$OUTLINE" 0.55);

@define-color green ${ACCENT2};
@define-color yellow ${ACCENT3};
@define-color red ${ERROR};
EOF

# Rofi colors
cat > "$HOME/.config/rofi/colors.rasi" << EOF
/* Auto-generated by matugen */

* {
    bg:             $(hex_to_rgba "$SURFACE" 0.9);
    bg-alt:         $(hex_to_rgba "$SURFACE_CONTAINER" 0.92);
    bg-hover:       $(hex_to_rgba "$SURFACE_CONTAINER_HIGH" 0.92);
    fg:             ${TEXT};
    fg-alt:         ${TEXT_MUTED};
    accent:         ${ACCENT};
    urgent:         ${ERROR};
    transparent:    #00000000;
    border-color:   $(hex_to_rgba "$OUTLINE" 0.35);
}
EOF

# Kitty colors
cat > "$HOME/.config/kitty/colors-hypraceelerator.conf" << EOF
# Auto-generated by matugen

foreground ${TEXT}
background ${BG}
cursor ${ACCENT}
cursor_text_color ${BG}
selection_foreground ${BG}
selection_background ${ACCENT}

color0 ${BG}
color1 ${ERROR}
color2 ${ACCENT2}
color3 ${ACCENT3}
color4 ${ACCENT}
color5 ${ACCENT3}
color6 ${ACCENT2}
color7 ${TEXT}

color8 ${OUTLINE}
color9 ${ERROR}
color10 ${ACCENT2}
color11 ${ACCENT3}
color12 ${ACCENT}
color13 ${ACCENT3}
color14 ${ACCENT2}
color15 ${TEXT}
EOF

# GTK color scheme preference
if command -v gsettings >/dev/null 2>&1 && [[ -n "${DBUS_SESSION_BUS_ADDRESS:-}" ]]; then
    if gsettings get org.gnome.desktop.interface color-scheme >/dev/null 2>&1; then
        if [[ "$MODE" == "dark" ]]; then
            gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' || true
        else
            gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' || true
        fi
    fi
fi

# Save state
cat > "$STATE_FILE" << EOF
# Auto-generated by theme-apply.sh
WALLPAPER="$WALLPAPER"
MODE="$MODE"
EOF

# Reload components
timeout 1s hyprctl reload 2>/dev/null || true
timeout 1s pkill -SIGUSR2 waybar 2>/dev/null || (pkill waybar 2>/dev/null && sleep 0.3 && waybar &)
timeout 1s swaync-client --reload-css 2>/dev/null || true

notify "Theme applied (${MODE})" normal
