#!/bin/bash
# Wallpaper Theme Manager - Complete System Theming
# Automatically generates and applies color schemes based on wallpaper
# Updates: Hyprland, Waybar, SwayNC, GTK, and more
# Usage: wallpaper-theme.sh <path-to-wallpaper> [transition-type]

WALLPAPER="$1"
TRANSITION="${2:-grow}"
CACHE_DIR="$HOME/.cache/wallpaper-theme"
COLORS_FILE="$CACHE_DIR/colors.sh"

# Ensure required directories exist
mkdir -p "$CACHE_DIR"
mkdir -p "$HOME/.config/hypr"
mkdir -p "$HOME/.config/waybar"
mkdir -p "$HOME/.config/swaync"

# Validate wallpaper
if [[ -z "$WALLPAPER" ]]; then
    notify-send "Wallpaper Theme" "Usage: wallpaper-theme.sh <path-to-image>" -u warning
    exit 1
fi

if [[ ! -f "$WALLPAPER" ]]; then
    notify-send "Wallpaper Theme" "File not found: $WALLPAPER" -u critical
    exit 1
fi

# Check for swww daemon
if ! pgrep -x swww-daemon &>/dev/null; then
    swww-daemon &
    sleep 0.5
fi

# Save current wallpaper for init script
mkdir -p "$HOME/.cache/wallpaper-theme"
echo "$WALLPAPER" > "$HOME/.cache/wallpaper-theme/last-wallpaper"

# Set wallpaper with swww
swww img "$WALLPAPER" \
    --transition-type "$TRANSITION" \
    --transition-duration 1.5 \
    --transition-fps 60 \
    --transition-bezier 0.65,0,0.35,1

# Generate colors using pywal
if command -v wal &>/dev/null; then
    echo "Generating colors with pywal..."
    wal -i "$WALLPAPER" -n -q -e
    source "$HOME/.cache/wal/colors.sh"
else
    notify-send "Wallpaper Theme" "Install pywal: yay -S python-pywal" -u warning
    exit 1
fi

# Helper: Convert hex to rgba
hex_to_rgba() {
    local hex="${1#\#}"
    local alpha="${2:-1}"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "rgba($r, $g, $b, $alpha)"
}

# Helper: Lighten/darken color
adjust_brightness() {
    local hex="${1#\#}"
    local percent="$2"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))

    if [[ $percent -gt 0 ]]; then
        r=$(( r + (255 - r) * percent / 100 ))
        g=$(( g + (255 - g) * percent / 100 ))
        b=$(( b + (255 - b) * percent / 100 ))
    else
        local abs_percent=$(( -percent ))
        r=$(( r * (100 - abs_percent) / 100 ))
        g=$(( g * (100 - abs_percent) / 100 ))
        b=$(( b * (100 - abs_percent) / 100 ))
    fi

    printf "#%02x%02x%02x" $r $g $b
}

# Determine luminance for dark/light detection
get_luminance() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "scale=4; (0.299*$r + 0.587*$g + 0.114*$b) / 255" | bc
}

LUMINANCE=$(get_luminance "$background" 2>/dev/null || echo "0.1")
IS_DARK=$(echo "$LUMINANCE < 0.5" | bc 2>/dev/null || echo "1")

# Set color variables
BG="$color0"
BG_LIGHT=$(adjust_brightness "$color0" 15)
BG_LIGHTER=$(adjust_brightness "$color0" 25)
FG="$color7"
FG_DIM="$color8"
ACCENT="$color1"
ACCENT2="$color2"
ACCENT3="$color3"
ACCENT4="$color4"

# ===== UPDATE HYPRLAND =====
cat > "$HOME/.config/hypr/colors-dynamic.conf" << EOF
# Auto-generated by wallpaper-theme.sh
# Colors extracted from: $(basename "$WALLPAPER")

\$accent1 = ${ACCENT}
\$accent2 = ${ACCENT2}

general {
    col.active_border = rgba(${ACCENT:1}ff) rgba(${ACCENT2:1}ff) 45deg
    col.inactive_border = rgba(${FG_DIM:1}40)
}
EOF

# ===== UPDATE WAYBAR COLORS =====
cat > "$HOME/.config/waybar/colors.css" << EOF
/* Auto-generated by wallpaper-theme.sh */
/* Colors from: $(basename "$WALLPAPER") */

@define-color bg-base $(hex_to_rgba "$BG" 0.75);
@define-color bg-surface $(hex_to_rgba "$BG_LIGHT" 0.9);
@define-color bg-hover rgba(255, 255, 255, 0.1);
@define-color bg-active $(hex_to_rgba "$ACCENT" 0.2);

@define-color text-primary ${FG};
@define-color text-secondary ${FG_DIM};

@define-color accent-primary ${ACCENT};
@define-color accent-secondary ${ACCENT2};
@define-color accent-tertiary ${ACCENT3};

@define-color warning #f9e2af;
@define-color critical #f38ba8;
@define-color success #a6e3a1;
EOF

# ===== UPDATE SWAYNC COLORS =====
cat > "$HOME/.config/swaync/colors.css" << EOF
/* Auto-generated by wallpaper-theme.sh */
/* Colors from: $(basename "$WALLPAPER") */

@define-color bg $(hex_to_rgba "$BG" 0.95);
@define-color bg-solid ${BG};
@define-color bg-hover $(hex_to_rgba "$BG_LIGHT" 0.95);
@define-color bg-focus $(hex_to_rgba "$BG_LIGHTER" 0.95);
@define-color bg-widget $(hex_to_rgba "$BG_LIGHT" 0.9);

@define-color text ${FG};
@define-color text-secondary ${FG_DIM};
@define-color text-dim $(adjust_brightness "$FG_DIM" -20);

@define-color accent ${ACCENT};
@define-color accent-light $(hex_to_rgba "$ACCENT" 0.2);
@define-color accent2 ${ACCENT2};

@define-color border rgba(255, 255, 255, 0.08);
@define-color border-light rgba(255, 255, 255, 0.12);

@define-color green #4ade80;
@define-color yellow #facc15;
@define-color red #ef4444;
EOF

# ===== UPDATE ROFI COLORS =====
if [ -d "$HOME/.config/rofi" ]; then
    cat > "$HOME/.config/rofi/colors.rasi" << EOF
/* Auto-generated by wallpaper-theme.sh */
/* Colors from: $(basename "$WALLPAPER") */

* {
    bg: ${BG};
    bg-alt: ${BG_LIGHT};
    fg: ${FG};
    fg-alt: ${FG_DIM};
    accent: ${ACCENT};
    urgent: #f38ba8;
}
EOF
fi

# ===== UPDATE GTK =====
if [[ "$IS_DARK" == "1" ]]; then
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null || true
else
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light' 2>/dev/null || true
fi

# ===== SAVE STATE =====
cat > "$COLORS_FILE" << EOF
# Current theme state - Generated $(date)
WALLPAPER="$WALLPAPER"
BG="$BG"
FG="$FG"
ACCENT="$ACCENT"
ACCENT2="$ACCENT2"
IS_DARK="$IS_DARK"
EOF

# ===== RELOAD COMPONENTS =====
hyprctl reload 2>/dev/null

# Reload waybar
pkill -SIGUSR2 waybar 2>/dev/null || (pkill waybar && sleep 0.3 && waybar &)

# Reload swaync
swaync-client --reload-css 2>/dev/null

notify-send "Theme Applied" "$(basename "$WALLPAPER")" -i "$WALLPAPER" -t 3000

echo "Theme applied successfully!"
echo "  Background: $BG"
echo "  Foreground: $FG"
echo "  Accent: $ACCENT"
